require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompromisesController do

  # This should return the minimal set of attributes required to create a valid
  # Compromise. As you add validations to Compromise, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "description" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompromisesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all compromises as @compromises" do
      compromise = Compromise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:compromises).should eq([compromise])
    end
  end

  describe "GET show" do
    it "assigns the requested compromise as @compromise" do
      compromise = Compromise.create! valid_attributes
      get :show, {:id => compromise.to_param}, valid_session
      assigns(:compromise).should eq(compromise)
    end
  end

  describe "GET new" do
    it "assigns a new compromise as @compromise" do
      get :new, {}, valid_session
      assigns(:compromise).should be_a_new(Compromise)
    end
  end

  describe "GET edit" do
    it "assigns the requested compromise as @compromise" do
      compromise = Compromise.create! valid_attributes
      get :edit, {:id => compromise.to_param}, valid_session
      assigns(:compromise).should eq(compromise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Compromise" do
        expect {
          post :create, {:compromise => valid_attributes}, valid_session
        }.to change(Compromise, :count).by(1)
      end

      it "assigns a newly created compromise as @compromise" do
        post :create, {:compromise => valid_attributes}, valid_session
        assigns(:compromise).should be_a(Compromise)
        assigns(:compromise).should be_persisted
      end

      it "redirects to the created compromise" do
        post :create, {:compromise => valid_attributes}, valid_session
        response.should redirect_to(Compromise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved compromise as @compromise" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compromise.any_instance.stub(:save).and_return(false)
        post :create, {:compromise => { "description" => "invalid value" }}, valid_session
        assigns(:compromise).should be_a_new(Compromise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compromise.any_instance.stub(:save).and_return(false)
        post :create, {:compromise => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested compromise" do
        compromise = Compromise.create! valid_attributes
        # Assuming there are no other compromises in the database, this
        # specifies that the Compromise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Compromise.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => compromise.to_param, :compromise => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested compromise as @compromise" do
        compromise = Compromise.create! valid_attributes
        put :update, {:id => compromise.to_param, :compromise => valid_attributes}, valid_session
        assigns(:compromise).should eq(compromise)
      end

      it "redirects to the compromise" do
        compromise = Compromise.create! valid_attributes
        put :update, {:id => compromise.to_param, :compromise => valid_attributes}, valid_session
        response.should redirect_to(compromise)
      end
    end

    describe "with invalid params" do
      it "assigns the compromise as @compromise" do
        compromise = Compromise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compromise.any_instance.stub(:save).and_return(false)
        put :update, {:id => compromise.to_param, :compromise => { "description" => "invalid value" }}, valid_session
        assigns(:compromise).should eq(compromise)
      end

      it "re-renders the 'edit' template" do
        compromise = Compromise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compromise.any_instance.stub(:save).and_return(false)
        put :update, {:id => compromise.to_param, :compromise => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested compromise" do
      compromise = Compromise.create! valid_attributes
      expect {
        delete :destroy, {:id => compromise.to_param}, valid_session
      }.to change(Compromise, :count).by(-1)
    end

    it "redirects to the compromises list" do
      compromise = Compromise.create! valid_attributes
      delete :destroy, {:id => compromise.to_param}, valid_session
      response.should redirect_to(compromises_url)
    end
  end

end
